# Exemplo 3 - Atividade em sala

Os valores da precipitação anual em College Station, Texas, de 1911 a 1979 são mostrados na Tabela.

Calcule:
* a) média amostral
* b) desvio padrão amostral
* c) coeficiente de assimetria amostral

dos dados para a precipitação anual em College Station, Texas, de 1970 a 1979. Os dados são fornecidos abaixo.

**Precipitação anual na College Station, Texas, 1911-1979 (pol)**

| Year | 1910 | 1920 | 1930 | 1940 | 1950 | 1960 | 1970 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 0 |     | 48.7 | 44.8 | 49.3 | 31.2 | 46.0 | 33.9 |
| 1 | 39.9 | 44.1 | 34.0 | 44.2 | 27.0 | 44.3 | 31.7 |
| 2 | 31.0 | 42.8 | 45.6 | 41.7 | 37.0 | 37.8 | 31.5 |
| 3 | 42.3 | 48.4 | 37.3 | 30.8 | 46.8 | 29.6 | 59.6 |
| 4 | 42.1 | 34.2 | 43.7 | 53.6 | 26.9 | 35.1 | 50.5 |
| 5 | 41.1 | 32.4 | 41.8 | 34.5 | 25.4 | 49.7 | 38.6 |
| 6 | 28.7 | 46.4 | 41.1 | 50.3 | 23.0 | 36.6 | 43.4 |
| 7 | 16.8 | 38.9 | 31.2 | 43.8 | 56.5 | 32.5 | 28.7 |
| 8 | 34.1 | 37.3 | 35.2 | 21.6 | 43.4 | 61.7 | 32.0 |
| 9 | 56.4 | 50.6 | 35.1 | 47.1 | 41.3 | 47.4 | 51.8 |

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy

In [2]:
# Baixa dados da College Station, Texas
!gdown 122MCZkRoniGlkFXnLJLTvKJcLu-lbcZW

Downloading...
From: https://drive.google.com/uc?id=122MCZkRoniGlkFXnLJLTvKJcLu-lbcZW
To: /content/p_College_Station_Texas.csv
100% 700/700 [00:00<00:00, 2.17MB/s]

In [3]:
df  = pd.read_csv('p_College_Station_Texas.csv', index_col= 0, sep =',')
df.index=pd.to_datetime(df.index,format='%Y')
df = df['1970':'1979']
df

            p(in)
Year
1970-01-01   33.9
1971-01-01   31.7
1972-01-01   31.5
1973-01-01   59.6
1974-01-01   50.5
1975-01-01   38.6
1976-01-01   43.4
1977-01-01   28.7
1978-01-01   32.0
1979-01-01   51.8

In [4]:
# média amostral
df.mean()

p(in)    40.17
dtype: float64

In [5]:
# desvio padrão
df.std()

p(in)    10.629733
dtype: float64

In [6]:
# coeficiente de assimetria
df.skew()

p(in)    0.749367
dtype: float64